baseURL = "https://luisday.com"
languageCode = "en-us"
title = "Luis Day!"
theme = "luis-day"
removePathAccents = true


# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.svg"
# home = "Home"
# about = "About"
# service = "Services"
# contact = "Contact"

# Hero Area
[params.hero]
enable = true
bg = "images/mobile-bg.jpg"
mbg = "images/mobile-bg.jpg"
title = ""
subtitle = ""
btnText = ""

# counter
disableCountdown = false
countdownYear = "2025"
countdownMonth = "05"
countdownDay = "03"

# About Section
[params.about]
enable = true
heading = "Snacky Boys of the World, Unite!"
description = "Luis Day: A celebration of unparalleled grandeur, where traditions of merriment, movement, and mildly chaotic debates converge into a singular moment of destiny."

[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/4.jpg"
[[params.about.sliderItem]]
image = "images/about/5.jpg"
[[params.about.sliderItem]]
image = "images/about/6.jpg"
[[params.about.sliderItem]]
image = "images/about/7.jpg"
[[params.about.sliderItem]]
image = "images/about/8.jpg"
[[params.about.sliderItem]]
image = "images/about/9.jpg"
[[params.about.sliderItem]]
image = "images/about/10.jpg"


# Service Section
[params.service]
enable = true
title = "What Every Snacky Boy Waits All Year For"
subtitle = "On Luis Day, Snacky Boys from near and far unite to partake in a carefully curated agenda of activities, each designed to elevate the human spirit, challenge the oppressive structures of late-stage capitalism, and honor the profound legacy of Luis:"
[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "fa-solid fa-champagne-glasses"
title = "Merry Making"
description = "Collective joy is an act of rebellion. Laugh in the face of hierarchy, for the revolution will not be solemn."
delay = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "fa fa-music"
title = "Boogeying"
description = "A rhythmic expression of joy, where bodies move in ways that defy physics and reason. Dancing is not merely encouraged; it is mandated by the invisible, immutable Snacky Boy Code."
delay = "0.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-anchor2"
title = "Debating"
description = "Spirited discussions on any topic of great import, except time, every snacky boy knows to not talk about time, and whether or not Ireland is a part of the British Isles."
delay = "0.4s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-globe"
title = "Pasta Making"
description = "Witness the alchemy of flour, eggs, and guanciale transform into ethereal bowls of carbonara and amatriciana."
delay = "0.6s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-strategy"
title = "Light-Hearted Italian Conversations"
description = "Casual discussions conducted in melodic Italian tones. To outsiders, it may sound like fiery disagreements. To insiders, it’s just Tuesday."
delay = "0.8s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-circle-compass"
title = "Hopefully Skyrim & Zombies"
description = "Should the technological stars align and the collective mood favor adventure, Luis may traverse the lands of Tamriel, slaying dragons and stealing sweet rolls, before seamlessly transitioning to fortifying barricades and fending off the undead hordes with his comrades."
delay = "1s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-anchor2"
title = "Naruto Watching"
description = "If the mood strikes and the snacks align, Luis might embark on yet another journey through the world of Naruto. Expect moments of deep reflection on the power of friendship, epic ninja battles, and the occasional tear shed over a particularly moving filler episode."
delay = "1.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-globe"
title = "Map Games"
description = "But only if you're Joe and Luis, or mildly autistic, or super autistic and just really good at masking."
delay = "1.5s"


# Call to Action Section
[params.cta]
enable = true
bg = "images/call-to-action.jpg"
title = "We are SnackyBoys"
subtitle = "We like to boogie and stuff"

[params.contact]
enable = true
title = "Connect With SnackyBoys in Your Area"
subtitle = ""
